/**
 * Export Service
 * Generates JSON and Markdown exports of analysis results
 */

class ExportService {
    static generateJsonExport(analysisData) {
        const exportData = {
            exportedAt: new Date().toISOString(),
            version: '2.0',
            analysis: analysisData,
        };

        return JSON.stringify(exportData, null, 2);
    }

    static generateMarkdownReport(analysisData) {
        const aiAnalysis = analysisData.ai_analysis || {};
        const atsScore = analysisData.ats_score || {};
        const skills = analysisData.skills || {};
        const roadmap = analysisData.roadmap || {};

        const now = new Date();
        const formattedDate = now.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });

        let report = `# Resume Analysis Report

**Generated:** ${formattedDate}

---

## Overall Score: ${aiAnalysis.overallScore || 0}/100

${aiAnalysis.summary || ''}

---

## Detailed Scores

| Category | Score |
|----------|-------|
| Formatting | ${aiAnalysis.scores?.formatting || 0}/100 |
| Content | ${aiAnalysis.scores?.content || 0}/100 |
| Experience | ${aiAnalysis.scores?.experience || 0}/100 |
| Skills | ${aiAnalysis.scores?.skills || 0}/100 |
| Education | ${aiAnalysis.scores?.education || 0}/100 |
| Impact | ${aiAnalysis.scores?.impact || 0}/100 |

---

## ATS Compatibility Score: ${atsScore.overall_score || 0}/100

**Status:** ${atsScore.ats_friendly ? '✅ ATS Friendly' : '⚠️ Needs Improvement'}

### Category Breakdown

`;

        // Add ATS category scores
        for (const [category, score] of Object.entries(atsScore.category_scores || {})) {
            const formattedCategory = category.replace(/_/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase());
            report += `- **${formattedCategory}:** ${score.toFixed(1)}/100\n`;
        }

        report += '\n---\n\n## Strengths\n\n';
        (aiAnalysis.strengths || []).forEach((strength, i) => {
            report += `${i + 1}. ${strength}\n`;
        });

        report += '\n## Areas for Improvement\n\n';
        (aiAnalysis.improvements || []).forEach((improvement, i) => {
            report += `${i + 1}. ${improvement}\n`;
        });

        report += '\n---\n\n## Skills Analysis\n\n';
        report += `**Detected Role:** ${skills.detected_role || 'N/A'}\n\n`;

        const currentSkills = skills.current || {};
        report += `**Total Technical Skills:** ${currentSkills.total_technical || 0}\n`;
        report += `**Total Soft Skills:** ${currentSkills.total_soft || 0}\n\n`;

        report += '### Recommended Skills to Learn\n\n';
        (skills.suggested || []).forEach((skill) => {
            report += `- ${skill}\n`;
        });

        report += '\n---\n\n## Learning Roadmap\n\n';
        report += `**Estimated Time:** ${roadmap.total_time || 'N/A'}\n\n`;

        (roadmap.phases || []).forEach((phase) => {
            report += `### Phase ${phase.phase}: ${phase.name}\n`;
            report += `**Duration:** ${phase.duration}\n`;
            report += `**Focus:** ${phase.focus}\n`;
            report += `**Skills:** ${phase.skills?.join(', ') || ''}\n\n`;
        });

        report += '\n---\n\n## Recommendations\n\n';
        (aiAnalysis.recommendations || []).forEach((rec, i) => {
            report += `${i + 1}. ${rec}\n`;
        });

        report += '\n---\n\n*Report generated by Resume Analyzer AI*\n';

        return report;
    }

    static generateSummaryStats(analysisData) {
        const aiAnalysis = analysisData.ai_analysis || {};
        const atsScore = analysisData.ats_score || {};
        const skills = analysisData.skills || {};

        return {
            overallScore: aiAnalysis.overallScore || 0,
            atsScore: atsScore.overall_score || 0,
            totalSkills: skills.current?.total_technical || 0,
            skillGap: skills.skill_gap_count || 0,
            strengthsCount: aiAnalysis.strengths?.length || 0,
            improvementsCount: aiAnalysis.improvements?.length || 0,
            atsCompatible: atsScore.ats_friendly || false,
            detectedRole: skills.detected_role || 'Unknown',
        };
    }
}

export default ExportService;
